vich_uploader:
    db_driver: orm

    mappings:
        users_image:
            uri_prefix: /images/users_profile
            upload_destination: '%kernel.project_dir%/public/images/users_profile'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

           